/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-14.glb --transform --types 
Files: macbook-14.glb [629.72KB] > /Users/admin/Work/next-js-projects/apple-product-page/apple-page-copy/public/models/macbook-14-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/
"use client";
import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";
import useMacbookStore from "@/app/store";
import { noChangeParts } from "@/app/constants";
import { Object3D, Mesh, Material } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_127: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    zhGRTuGrQoJflBD: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    lmWQsEjxpsebDlK: THREE.MeshStandardMaterial;
    LtEafgAVRolQqRw: THREE.MeshStandardMaterial;
    iyDJFXmHelnMTbD: THREE.MeshStandardMaterial;
    eJObPwhgFzvfaoZ: THREE.MeshStandardMaterial;
    nDsMUuDKliqGFdU: THREE.MeshStandardMaterial;
    CRQixVLpahJzhJc: THREE.MeshStandardMaterial;
    YYwBgwvcyZVOOAA: THREE.MeshStandardMaterial;
    SLGkCohDDelqXBu: THREE.MeshStandardMaterial;
    WnHKXHhScfUbJQi: THREE.MeshStandardMaterial;
    fNHiBfcxHUJCahl: THREE.MeshStandardMaterial;
    LpqXZqhaGCeSzdu: THREE.MeshStandardMaterial;
    gMtYExgrEUqPfln: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    JvMFZolVCdpPqjj: THREE.MeshStandardMaterial;
    sfCQkHOWyrsLmor: THREE.MeshStandardMaterial;
    ZCDwChwkbBfITSW: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};
function isMesh(object: Object3D): object is Mesh {
  return (object as Mesh).isMesh === true;
}

export function MacBookModel14(props: JSX.IntrinsicElements["group"]) {
  const texture = useTexture("/screen.png");
  const { nodes, materials, scene } = useGLTF(
    "/models/macbook-14-transformed.glb"
  ) as GLTFResult;

  const { color } = useMacbookStore();

  useEffect(() => {
    scene.traverse((child: Object3D) => {
      if (isMesh(child)) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new THREE.Color(color);
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.zhGRTuGrQoJflBD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.PaletteMaterial002}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.lmWQsEjxpsebDlK}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.LtEafgAVRolQqRw}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.iyDJFXmHelnMTbD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.eJObPwhgFzvfaoZ}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.nDsMUuDKliqGFdU}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.CRQixVLpahJzhJc}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.YYwBgwvcyZVOOAA}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.SLGkCohDDelqXBu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.WnHKXHhScfUbJQi}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.fNHiBfcxHUJCahl}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.LpqXZqhaGCeSzdu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.gMtYExgrEUqPfln}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.PaletteMaterial003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_107.geometry}
        material={materials.JvMFZolVCdpPqjj}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_123.geometry}
        material={materials.sfCQkHOWyrsLmor}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Object_127.geometry}
        material={materials.ZCDwChwkbBfITSW}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/macbook-14-transformed.glb");
